{% set version = "0.9.1" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/descarteslabs/descarteslabs-{{ version }}.tar.gz
  sha256: 7e84f7439a832018fa01375addd0d3082c2c8066197de196f67f0d76da254e9b

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - cachetools
    - cloudpickle
    - six
    - requests >=2.16.0

test:
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Descartes Labs Python Library'

extra:
  recipe-maintainers:
    - ocefpaf
