{% set version = "0.28.1" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/descarteslabs/descarteslabs-{{ version }}.tar.gz
  sha256: 4a697cd8a8b0ec53d6a525c23b3ec596fa9a1f50fea3ffcb680306284a31a4c7

build:
  number: 0
  skip: True  # [win and py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - descarteslabs = descarteslabs.client.scripts.__main__:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - cloudpickle ==0.4.0
    - six >=1.12
    - cachetools >=2.0.1
    - futures  # [py27]
    - geojson >=2.4.1
    - shapely >=1.6.3,<2
    - affine >=2.2.1
    - pyarrow ==0.13.0
    - grpcio >=1.16.1,<2
    - protobuf ==3.8.0,<4
    - requests >=2.20.1,<3

test:
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Descartes Labs Python Library'

extra:
  recipe-maintainers:
    - ocefpaf
