{% set version = "0.16.0" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/descarteslabs/descarteslabs-{{ version }}.tar.gz
  sha256: 87f9ebf2e87a199355e6aed6e9abe316aee30d8b889719dcedbb837577990591

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - descarteslabs = descarteslabs.client.scripts.__main__:main

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - cachetools >=2.0.1
    - cloudpickle =0.4.0
    - six
    - requests >=2.16.0

test:
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Descartes Labs Python Library'

extra:
  recipe-maintainers:
    - ocefpaf
