{% set version = "0.25.0" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/descarteslabs/descarteslabs-{{ version }}.tar.gz
  sha256: 815c4361ddab26cfd1b52990f6d90bf358507331bcaf5f6cd26baa21cede0eca

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - descarteslabs = descarteslabs.client.scripts.__main__:main

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - cachetools >=2.0.1
    - cloudpickle =0.4.0
    - six
    - cachetools >=2.0.1
    - geojson >=2.4.0
    - shapely >=1.6.3,<2
    - affine >=2.2.1
    - requests >=2.20.1,<3

test:
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Descartes Labs Python Library'

extra:
  recipe-maintainers:
    - ocefpaf
