{% set version = "0.11.1" %}

package:
  name: descarteslabs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/descarteslabs/descarteslabs-{{ version }}.tar.gz
  sha256: a07cbd5b2f194b7721ce781b12292684ffab0e4b8e5821000ff9ccfe520ae6c8

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - cachetools
    - cloudpickle
    - futures  # [py2k]
    - six
    - requests >=2.16.0

test:
  imports:
    - descarteslabs

about:
  home: https://github.com/descarteslabs/descarteslabs-python
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Descartes Labs Python Library'

extra:
  recipe-maintainers:
    - ocefpaf
