travis:
  secure:
    BINSTAR_TOKEN: YUlA2gC08RGQ3F/phpBLYaacjHGsNPoMG0nfMD1lBtcUdnNpTIrhPiI8lkd5GPjByodWBhBhcCrOvZz6VqZRRH6tvM1zyS6ZuoIJ0sD5CXDh31zozPm1okgk/9O1Qhkuwua+kwzN2R+lCUyXtKmcf1dR6ZtQKnBqDvOnJh9Biv4QPB6Lx7p4EKCXozn9O8QW6TAxpbgjIWV3QM8/oYQDFw/BHzZ2NQiu8VtO56a2UJfimLYxVxiTP6Cd9IbU0jJIZ0Bgo9j7qgG1BOsMoPouDsQd5KdWLdFN8IoMMw3NxQlqc5ZEA4XesZyWyXMnCdk3QGpJesUAw+tCx8CkcUB7IsJYraIMKjGLGa6XA8BaM6EhiOnwbDqKE1B4+EexPxQxcJEGyIBLshTQjy8mVjUuvlt2YOFYLtTX6LhepKR9d4uiukkemuyIkPPUxpw1V+aN61lGEK82LwZ3V45iatdsLMa+LivUm2Y9ps7B66dcITkhmrUMqHW1A3MuSbxts46lUuqnrkmVhrHsI/be9Fpuq4JVYCpOgqGJP8WRuXkdfi2gH5ChQ453v2g29Y1Oea8dr7lxJC+Rv+/CHkpZJEaWPv5ZvJ5DxDzf2JTsq4I2xOurAvaKJHchrDlwjKiYhQA5qxeD7fWeni8Dz/IH1cEUUb+9pEG4sIeS1tL41GK8Fwc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
